steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "${_IMAGE}", "-f", "apps/frontend/Dockerfile", "."]
images:
  - "${_IMAGE}"
substitutions:
  _IMAGE: "REGION-docker.pkg.dev/PROJECT_ID/bestvision/frontend:stg"
options:
  logging: CLOUD_LOGGING_ONLY
